name: ML CI/CT/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  testing:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install deps
      run: |
        pip install -r requirements.txt
        pip install flake8

    - name: Lint
      run: flake8 src/


  train-eval:
    needs: testing
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install deps
      run: pip install -r requirements.txt

    - name: Train
      run: python src/train.py

    - name: Evaluate
      run: python src/evaluate.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ml-artifacts
        path: |
          model/
          data/split/


  docker:
    needs: train-eval
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: ml-artifacts

    - name: Docker login
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
        -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build image
      run: docker build -t surbhibagad/soil-ml:latest .

    - name: Push image
      run: docker push surbhibagad/soil-ml:latest